// Auth states
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

// Profile states
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL'

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR_SUCCESS'
export const UPDATE_USER_AVATAR_FAIL = 'UPDATE_USER_AVATAR_FAIL'

export const DELETE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR_SUCCESS'
export const DELETE_USER_AVATAR_FAIL = 'UPDATE_USER_AVATAR_FAIL'


// Reset password
export const SEND_RESET_SUCCESS = 'SEND_RESET_SUCCESS'
export const SEND_RESET_FAIL = 'SEND_RESET_FAIL'

export const CHECK_DEPENDENCY_SUCCESS = 'CHECK_DEPENDENCY_SUCCESS'
export const CHECK_DEPENDENCY_FAIL = 'CHECK_DEPENDENCY_FAIL'


// Dashboard
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS'
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL'

export const UPLOAD_NEW_FILE_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS'
export const UPLOAD_NEW_FILE_FAIL = 'CREATE_NEW_FOLDER_FAIL'

export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS'
export const GET_FILES_FAIL = 'GET_FILES_FAIL'